image: node:latest

stages:
  - build
  - test

build:
  image: maven:3.8.1-openjdk-16
  stage: build
  artifacts:
    paths:
      - Group2/target
  script: mvn clean install

test:
  image: maven:3.8.1-openjdk-16
  stage: test
  artifacts:
    when: always
    reports:
      junit:
        - Group2/target/surefire-reports/TEST-*.xml
  script: mvn verify
