image: node:latest

stages:
  - build
  - test

buildStep:
  image: maven:3.8.1-openjdk-16
  stage: build
  tags:
    - bms_group2
  artifacts:
    paths:
      - Group2/target
  script: mvn clean install

testStep:
  image: maven:3.8.1-openjdk-16
  stage: test
  tags:
    - bms_group2
  artifacts:
    when: always
    reports:
      junit:
        - Group2/target/surefire-reports/TEST-*.xml
  script: mvn verify
